[package]
name = "omni-desktop"
version = "0.1.0"
edition = "2021"
description = "OMNI local personal context interface"
license = "AGPL-3.0-only"

[workspace]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-global-shortcut = "2"

[features]
custom-protocol = ["tauri/custom-protocol"]
